name = "pansou2cf"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
AUTH_ENABLED = "false"
AUTH_USERS = ""
AUTH_JWT_SECRET = ""
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin"
REGISTER_CODE = ""
CHANNELS = "tgsearchers6"
ASYNC_PLUGIN_ENABLED = "true"
ENABLED_PLUGINS = "pansearch,yunso,alupan"
ASYNC_RESPONSE_TIMEOUT = "4"
PLUGIN_TIMEOUT = "8"
