import type { PluginConfig } from './config-engine';

// Plugin configurations: all 87+ search sources with proper parsing mode
// mode 'json' uses JSON API parsing, 'html' uses multi-strategy HTML parsing, 'auto' detects
export const pluginConfigs: PluginConfig[] = [
  // ── Priority 1: Top sources with dedicated plugins (not used by config engine) ──
  { name: 'pansearch', priority: 1, searchUrl: 'https://www.pansearch.me/search?keyword={keyword}' },

  // ── Priority 3: High-quality sources ──
  { name: 'yunso', priority: 3, searchUrl: 'https://www.yunso.net/index/user/s?kw={keyword}', mode: 'html' },
  { name: 'alupan', priority: 3, searchUrl: 'https://www.alupan.net/search?keyword={keyword}', mode: 'html' },

  // JSON API sources with known structure
  { name: 'haisou', priority: 3, searchUrl: 'https://www.haisou.net/search?q={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'sousou', priority: 3, searchUrl: 'https://www.sousou.top/search?q={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'mikuclub', priority: 3, searchUrl: 'https://mikuclub.net/wp-json/wp/v2/posts?search={keyword}&per_page=30', mode: 'json' },
  { name: 'miaoso', priority: 4, searchUrl: 'https://www.miaoso.com/api/search?q={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'ouge', priority: 4, searchUrl: 'https://www.ouge.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data.list' },
  { name: 'feikuai', priority: 4, searchUrl: 'https://www.feikuai.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'xdyh', priority: 4, searchUrl: 'https://www.xdyh.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'zhizhen', priority: 4, searchUrl: 'https://www.zhizhen.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data.items' },
  { name: 'bixin', priority: 5, searchUrl: 'https://www.bixin.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'wanou', priority: 4, searchUrl: 'https://www.wanou.net/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'meitizy', priority: 5, searchUrl: 'https://www.meitizy.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'nsgame', priority: 5, searchUrl: 'https://www.nsgame.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'quark4k', priority: 5, searchUrl: 'https://www.quark4k.com/api/search?keyword={keyword}', mode: 'json', jsonResultPath: 'data' },
  { name: 'discourse', priority: 5, searchUrl: 'https://www.discourse.com/search?q={keyword}', mode: 'json' },

  // ── Priority 4: Standard HTML sources ──
  { name: 'pan666', priority: 4, searchUrl: 'https://pan666.net/search?keyword={keyword}', mode: 'html' },
  { name: 'panlian', priority: 4, searchUrl: 'https://www.panlian.xyz/search?kw={keyword}', mode: 'html' },
  { name: 'panta', priority: 4, searchUrl: 'https://www.panta.top/search?keyword={keyword}', mode: 'html' },
  { name: 'panwiki', priority: 4, searchUrl: 'https://www.panwiki.com/search?q={keyword}', mode: 'html' },
  { name: 'panzun', priority: 4, searchUrl: 'https://www.panzun.com/search?keyword={keyword}', mode: 'html' },
  { name: 'panyq', priority: 4, searchUrl: 'https://www.panyq.com/search?keyword={keyword}', mode: 'html' },
  { name: 'quarksoo', priority: 4, searchUrl: 'https://www.quarksoo.com/search?keyword={keyword}', mode: 'html' },
  { name: 'quarktv', priority: 4, searchUrl: 'https://www.quarktv.com/search?keyword={keyword}', mode: 'html' },
  { name: 'qupansou', priority: 4, searchUrl: 'https://www.qupansou.com/s?kw={keyword}', mode: 'html' },
  { name: 'qupanshe', priority: 4, searchUrl: 'https://www.qupanshe.com/search?keyword={keyword}', mode: 'html' },
  { name: 'xdpan', priority: 4, searchUrl: 'https://www.xdpan.com/search?keyword={keyword}', mode: 'html' },
  { name: 'xiaoji', priority: 4, searchUrl: 'https://www.xiaoji.com/search?q={keyword}', mode: 'html' },
  { name: 'xiaozhang', priority: 4, searchUrl: 'https://www.xiaozhang.com/search?keyword={keyword}', mode: 'html' },
  { name: 'yunsou', priority: 4, searchUrl: 'https://www.yunsou.com/s?q={keyword}', mode: 'html' },
  { name: 'shandian', priority: 4, searchUrl: 'https://www.shandian.com/search?keyword={keyword}', mode: 'html' },
  { name: 'sdso', priority: 4, searchUrl: 'https://www.sdso.com/search?q={keyword}', mode: 'html' },
  { name: 'u3c3', priority: 4, searchUrl: 'https://www.u3c3.com/search?keyword={keyword}', mode: 'html' },
  { name: 'xb6v', priority: 4, searchUrl: 'https://www.xb6v.com/search?keyword={keyword}', mode: 'html' },
  { name: 'qiwei', priority: 4, searchUrl: 'https://www.qiwei.com/search?keyword={keyword}', mode: 'html' },
  { name: 'yiove', priority: 4, searchUrl: 'https://www.yiove.com/search?q={keyword}', mode: 'html' },
  { name: 'yuhuage', priority: 4, searchUrl: 'https://www.yuhuage.com/search?keyword={keyword}', mode: 'html' },
  { name: 'yulinshufa', priority: 4, searchUrl: 'https://www.yulinshufa.com/search?keyword={keyword}', mode: 'html' },
  { name: 'zxzj', priority: 4, searchUrl: 'https://www.zxzj.com/search?keyword={keyword}', mode: 'html' },

  // ── Priority 5: Other sources ──
  { name: 'ahhhhfs', priority: 5, searchUrl: 'https://www.ahhhhfs.com/search?keyword={keyword}', mode: 'html' },
  { name: 'aikanzy', priority: 5, searchUrl: 'https://www.aikanzy.com/search?keyword={keyword}', mode: 'html' },
  { name: 'ash', priority: 5, searchUrl: 'https://www.ash.com/search?keyword={keyword}', mode: 'html' },
  { name: 'cldi', priority: 5, searchUrl: 'https://www.cldi.com/search?keyword={keyword}', mode: 'html' },
  { name: 'clmao', priority: 5, searchUrl: 'https://www.clmao.com/search?keyword={keyword}', mode: 'html' },
  { name: 'clxiong', priority: 5, searchUrl: 'https://www.clxiong.com/search?keyword={keyword}', mode: 'html' },
  { name: 'cyg', priority: 5, searchUrl: 'https://www.cyg.com/search?keyword={keyword}', mode: 'html' },
  { name: 'daishudj', priority: 5, searchUrl: 'https://www.daishudj.com/search?keyword={keyword}', mode: 'html' },
  { name: 'ddys', priority: 5, searchUrl: 'https://www.ddys.com/search?keyword={keyword}', mode: 'html' },
  { name: 'djgou', priority: 5, searchUrl: 'https://www.djgou.com/search?keyword={keyword}', mode: 'html' },
  { name: 'duanjuw', priority: 5, searchUrl: 'https://www.duanjuw.com/search?keyword={keyword}', mode: 'html' },
  { name: 'duoduo', priority: 5, searchUrl: 'https://www.duoduo.com/search?keyword={keyword}', mode: 'html' },
  { name: 'dyyj', priority: 5, searchUrl: 'https://www.dyyj.com/search?keyword={keyword}', mode: 'html' },
  { name: 'dyyjpro', priority: 5, searchUrl: 'https://www.dyyjpro.com/search?keyword={keyword}', mode: 'html' },
  { name: 'erxiao', priority: 5, searchUrl: 'https://www.erxiao.com/search?keyword={keyword}', mode: 'html' },
  { name: 'fox4k', priority: 5, searchUrl: 'https://www.fox4k.com/search?keyword={keyword}', mode: 'html' },
  { name: 'gaoqing888', priority: 5, searchUrl: 'https://www.gaoqing888.com/search?keyword={keyword}', mode: 'html' },
  { name: 'gying', priority: 5, searchUrl: 'https://www.gying.com/search?keyword={keyword}', mode: 'html' },
  { name: 'hdmoli', priority: 5, searchUrl: 'https://www.hdmoli.com/search?keyword={keyword}', mode: 'html' },
  { name: 'hdr4k', priority: 5, searchUrl: 'https://www.hdr4k.com/search?keyword={keyword}', mode: 'html' },
  { name: 'huban', priority: 5, searchUrl: 'https://www.huban.com/search?keyword={keyword}', mode: 'html' },
  { name: 'hunhepan', priority: 5, searchUrl: 'https://www.hunhepan.com/search?keyword={keyword}', mode: 'html' },
  { name: 'javdb', priority: 5, searchUrl: 'https://www.javdb.com/search?q={keyword}', mode: 'html' },
  { name: 'jikepan', priority: 5, searchUrl: 'https://www.jikepan.com/search?keyword={keyword}', mode: 'html' },
  { name: 'jsnoteclub', priority: 5, searchUrl: 'https://www.jsnoteclub.com/search?keyword={keyword}', mode: 'html' },
  { name: 'jupansou', priority: 5, searchUrl: 'https://www.jupansou.com/search?keyword={keyword}', mode: 'html' },
  { name: 'jutoushe', priority: 5, searchUrl: 'https://www.jutoushe.com/search?keyword={keyword}', mode: 'html' },
  { name: 'kkmao', priority: 5, searchUrl: 'https://www.kkmao.com/search?keyword={keyword}', mode: 'html' },
  { name: 'kkv', priority: 5, searchUrl: 'https://www.kkv.com/search?q={keyword}', mode: 'html' },
  { name: 'labi', priority: 5, searchUrl: 'https://www.labi.com/search?keyword={keyword}', mode: 'html' },
  { name: 'leijing', priority: 5, searchUrl: 'https://www.leijing.com/search?keyword={keyword}', mode: 'html' },
  { name: 'libvio', priority: 5, searchUrl: 'https://www.libvio.com/search?keyword={keyword}', mode: 'html' },
  { name: 'lingjisp', priority: 5, searchUrl: 'https://www.lingjisp.com/search?keyword={keyword}', mode: 'html' },
  { name: 'lou1', priority: 5, searchUrl: 'https://www.lou1.com/search?keyword={keyword}', mode: 'html' },
  { name: 'melost', priority: 5, searchUrl: 'https://www.melost.com/search?keyword={keyword}', mode: 'html' },
  { name: 'mizixing', priority: 5, searchUrl: 'https://www.mizixing.com/search?keyword={keyword}', mode: 'html' },
  { name: 'muou', priority: 5, searchUrl: 'https://www.muou.com/search?keyword={keyword}', mode: 'html' },
  { name: 'nyaa', priority: 5, searchUrl: 'https://www.nyaa.com/search?q={keyword}', mode: 'html' },
  { name: 'pianku', priority: 5, searchUrl: 'https://www.pianku.com/search?keyword={keyword}', mode: 'html' },
  { name: 'qingying', priority: 5, searchUrl: 'https://www.qingying.com/search?keyword={keyword}', mode: 'html' },
  { name: 'qqpd', priority: 5, searchUrl: 'https://www.qqpd.com/search?keyword={keyword}', mode: 'html' },
  { name: 'susu', priority: 5, searchUrl: 'https://www.susu.com/search?keyword={keyword}', mode: 'html' },
  { name: 'thepiratebay', priority: 5, searchUrl: 'https://www.thepiratebay.com/search?q={keyword}', mode: 'html' },
  { name: 'weibo', priority: 5, searchUrl: 'https://www.weibo.com/search?q={keyword}', mode: 'html' },
  { name: 'wuji', priority: 5, searchUrl: 'https://www.wuji.com/search?keyword={keyword}', mode: 'html' },
  { name: 'xinjuc', priority: 5, searchUrl: 'https://www.xinjuc.com/search?keyword={keyword}', mode: 'html' },
  { name: 'xuexizhinan', priority: 5, searchUrl: 'https://www.xuexizhinan.com/search?keyword={keyword}', mode: 'html' },
  { name: 'xys', priority: 5, searchUrl: 'https://www.xys.com/search?keyword={keyword}', mode: 'html' },
  { name: 'ypfxw', priority: 5, searchUrl: 'https://www.ypfxw.com/search?keyword={keyword}', mode: 'html' },
];
